--  Dungeon of Despair
--
--  Author: Wolfgang Schreurs
--  info+despair@wolftrail.net

return {
    names = {
        'Balar',
        'Balin',
        'Bombur',
        'Dain',
        'Dargrim',
        'Donrin',
        'Dorn',
        'Durin',
        'Dwalin',
        'Dáilin',
        'Fangluin',
        'Fargrim',
        'Farin',
        'Frerin',
        'Garli',
        'Gimgar',
        'Gimli',
        'Glóin',
        'Mahal',
        'Oloric',
        'Thoradin',
        'Thorin',
        'Thorudin',
        'Thráin',
        'Travok',
    },    
    filters = {
        '-',
        '[gr]l$',
        '[dgnt]r$',
        '[fth]rg',
        'sw$',
        'm[lgb]$',
        'r[ng]$',
        'rng$',
        'nb$',
        'nbh',
        '[gd]rd',
        'lj$',
        '[ai]$',
        'krlh',
        'cl[dhj]',
        'hld',
        'rld',
        '.{7,}',
        '(.)\\1\\1',
        '(?i)\b[b-df-hj-np-tv-z]+\\b',
    },
}
