--  Dungeon of Despair
--
--  Author: Wolfgang Schreurs
--  info+despair@wolftrail.net

return {
    names = {
        'Moira',
        'Anbera',
        'Audhild',
        'Bolhild',
        'Helgret',
        'Helja',
        'Hlin',
        'Kristryd',
        'Mardred',
        'Nora',
        'Riswynn',
        'Maeve',
        'Orlaigh',
        'Eimear',
        'Laoise',
        'Aoibhe',
        'Fiadh',
        'Áine',
        'Sinead',
        'Eabha',
        'Aisling',
        'Clodagh',
        'Cara',
        'Roisin',
        'Niamh',
        'Ciara',
        'Saoirse',
        'Caoimhe',
        'Aoife',
        'Shannon',
        'Mairead',
        'Caragh',
        'Riona',
        'Eireann',
    },
    filters = {
        '-',
        '[gr]l$',
        '[dgnt]r$',
        '[fth]rg',
        'sw$',
        '[bcfgjklmpqrstvwxyz]$',
        'm[lgb]$',
        'r[ng]$',
        'rng$',
        'nb$',
        'ghi',
        'nbh',
        '[gd]rd',
        'oioi',
        'lj$',
        'krlh',
        'cl[dhj]',
        'hld',
        'rld',
        '.{7,}',
        '(.)\\1\\1',
        '(?i)\b[b-df-hj-np-tv-z]+\\b',
    },
}
