--  Dungeon of Despair
--
--  Author: Wolfgang Schreurs
--  info+despair@wolftrail.net

return {
    names = {
        'Tanta',
        'Yolanda',
        'Regina',
        'Rhoda',
        'Rose',
        'Ruby',
        'Selina',
        'Matilda',
        'Gerda',
        'Gilly',
        'Arabella',
        'Bertha',
        'Cara',
        'Cora',
        'Daisy',
        'Dina',
        'Linda',
        'Malva',
        'Hilda',
        'Pansy',
        'Pearl',
        'Peony',
        'Lalia',
        'Mentha',
        'Mimosa',
        'Chica',
        'Estella',
        'Duenna',
        'Rosa',
        'Belba',
        'Amaranth',
    },
    filters = {
        '-',
        '.{7,}',
        'br[drgm]',
        '[bcdfghjklmpqrstvwxz]$',
        'dw$',
        'lb$',
        'll[vc]',
        '[rs]mw',
        'dr[dfw]',
        'gll',
        'gr[md]',
        '[dg]rg',
        'bl[blc]',
        '(.)\\1\\1',
        '(?i)\b[b-df-hj-np-tv-z]+\\b',
    },
}
