--  Dungeon of Despair
--
--  Author: Wolfgang Schreurs
--  info+despair@wolftrail.net

return {
    names = {
        'Andwise',
        'Balbo',
        'Bilbo',
        'Blanco',
        'Briffo',
        'Bruno',
        'Caradoc',
        'Cerdic',
        'Ceredic',
        'Drogo',
        'Déagol',
        'Falco',
        'Gormadoc',
        'Gruffo',
        'Iago',
        'Jago',
        'Largo',
        'Merry',
        'Mosco',
        'Polo',
        'Robin',
        'Robur',
        'Rollo',
        'Samwise',
        'Saradoc',
        'Sméagol',
        'Tobias',
        'Vigo',
        'Will',
    },
    filters = {
        '-',
        '.{7,}',
        'br[drgm]',
        'dw$',
        'lb$',
        '[ayi]$',
        'll[vc]',
        '[rs]mw',
        '[rd]rd',
        'gr[md]',
        '[dg]rg',
        'bl[blc]',
        '(.)\\1\\1',
        '(?i)\b[b-df-hj-np-tv-z]+\\b',
    },
}
