--  Dungeon of Despair
--
--  Author: Wolfgang Schreurs
--  info+despair@wolftrail.net

return {
    names = {
        'Adair',
        'Altair',
        'Caspian',
        'Cassius',
        'Corbin',
        'Darius',
        'Destin',
        'Drystan',
        'Fineas',
        'Gearwyn',
        'Hasperos',
        'Ignatius',
        'Korbin',
        'Liron',
        'Lucien',
        'Marius',
        'Mathieu',
        'Neirin',
        'Oisin',
        'Orion',
        'Remus',
        'Sabastian',
        'Serian',
        'Sirius',
        'Séverin',
        'Tearlach',
        'Thaniel',
        'Torian',
        'Torin',
        'Urien',
        'Vasilis',
        'Zarek',
        'Zephyr',
    },
    filters = {
        '-',
        '(.)\\1$',
        'sp$',
        '[aeiu]$',
        '(.)\\1\\1',
        '(?i)\b[b-df-hj-np-tv-z]+\\b',
    },
}
